apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hk7idwsik-python 
  janus-idp.io/tekton: hk7idwsik-python
  backstage.io/kubernetes-id: hk7idwsik-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hk7idwsik-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  