apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hk7idwsik-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hk7idwsik-python 
  name: hk7idwsik-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hk7idwsik-python 
